name: "Status Page: Zabbix Event Processor"

on:
  repository_dispatch:
    types: [zabbix-alert]

jobs:
  process-zabbix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Zabbix Parser
        env:
          PAYLOAD: ${{ json.encode(github.event.client_payload) }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/status_engine/parse_zabbix.py
